### PR TITLE
snipers can now randomly high roll and crit enemies

### PR DESCRIPTION
**Pull request by Kr1s1m**
- SEAS Sniper and Ada Lovelace can now "high roll" and critically strike based on random chance
- SEAS Sniper and Ada Lovelace have separate critical damage modifiers (factors) for easier balance
- Red particles appear around projectile firing character after successfully damaging an enemy (TakeDmg)
- "High roll" chance is based on actual level and the level gets -1 penalty when the sniper is on transport
- Lvl 0 -> 3% chance to "highroll"
- Lvl 1 -> 6% chance to "highroll"
- Lvl 2 -> 11% chance to "highroll"
- Lvl 3 -> 20% chance to "highroll"
- Lvl 4 -> 33% chance to "highroll"
- Lvl 5 -> 50% chance to "highroll"
- (Heroes have plot armor) deals heavy damage and one shots weaker infantry (headshot), bypasses machine armor (hatch), doubles against animals (hunter)
- TODO: Tweak multipliers (if needed), fix TT crash rpg leftover "seas_sniper=100" further (if needed), replace the used downlevel particle effect with unique (if possible)

### CODE REVIEW

**Comment by Kr1s1m** [comment]
image
DO NOT MERGE if those lines in CFightingObj are wrong

**Comment by Tatsukio** [comment]
Should be 7899, 11798, 16139
Math2 lib and ice for swimming harbours

**Comment by Kr1s1m** [comment]
So, 7899, 11810, 16139? or the removed red on each one?

**Comment by Kr1s1m** [comment]
Got it, red on each one

**Comment by Kr1s1m** [comment]
About TT changes:
Might still have some RangedDef "seas_sniper=100" leftover strings related to some crash rpg units. These need to be handled properly. I removed the same strings from heroes because they were only there to protect from the old and now removed CHTR=600 hard-coded bonus on sniper's weapon in TT.

**Review by OverVored — DISMISSED** [review]

**Comment by Tatsukio** [comment]
Readme?

**Comment by Kr1s1m** [comment]
ready

**Review by Tatsukio — APPROVED** [review]

**Pull request merged**
