### PR TITLE
new_build_menu

### PR DESCRIPTION
**Pull request by Tatsukio**
Each tribe now has its own build menu
Special focus disabled in CCommandBar

### CODE REVIEW

**Review by Kr1s1m — DISMISSED** [review]

**Comment by Tatsukio** [comment]
Each menu update (upgrade invented or building placed) broking whole cmd bar (units reselection needed)
Taslow and traider without buildings again
Some actions not showing if free specials option is on (tric actions and more)

**Review by Kr1s1m — COMMENTED** [review]
Ready to merge, or should we leave it open for now and add more to it?

**Comment by Tatsukio** [comment]
Heroes build menu should be fixed first. It was, but after merging with your changes it doesnt showup again

**Comment by Tatsukio** [comment]
So current problems is
- With tt stealing on, you can build other tribes buildings with yours players id, if your worker is first in the selection
- Menu flickering and collapsing after updating values (tt update, new building placed,upgrade invented and so on)
- Traders cant build zeppelin
- If several taslows with different tribes selected, only one menu will be available
- When multiselecting, some abilities are grayed out under certain conditions even if they can be used

**Pull request closed without merging**
